### ISSUE TITLE
add CODEOWNERS file to support master branch protection

### ISSUE THREAD

**Issue by joshua-rutherford** [greymatter-io/terraform-greymatter-ecs#3]
@zoemccormick and @sofiashalotenko you should add a CODEOWNERS file to the root of the repository that lists you as the owners at a minimum (https://github.com/greymatter-io/flux-production/blob/master/CODEOWNERS).  we will lock down the master branch so that all pull request require a review from someone listed in that file.

**Comment by zoemccormick** [comment]
closed with https://github.com/greymatter-io/terraform-greymatter-ecs/commit/bd148aae551ba2bd5a4848d1854d773ff455647c
